export enum Actions {
  ANY_ACTION = 'ANY_ACTION',
  CHATS_UPDATE = 'CHATS_UPDATE',
  ADD_USER_POPUP_SHOW = 'ADD_USER_POPUP_SHOW',
  CHNG_AVATAR_POPUP_SHOW = 'CHNG_AVATAR_POPUP_SHOW',
  DELETE_USER_FROM_CHAT = 'DELETE_USER_FROM_CHAT',
  ADD_MEDIA_SHOW_POPUP = 'ADD_MEDIA_SHOW_POPUP',
  GET_USER_DATA = 'GET_USER_DATA',
  LOGOUT_CLEAN_DATA = 'LOGOUT_CLEAN_DATA',
  UPDATE_AVATAR = 'UPDATE_AVATAR',
}
